Inertial:
  axis:
    - axis1:
        unit: 'rad/s'
        parameters:
        - rot_x
        - rot_y
        - rot_z
    - axis2:
        unit: 'm/s²'
        parameters:
          - a_x
          - a_y
          - a_z

Pressure:
  axis:
    - axis1:
        unit: 'hpa'
        parameters:
          - hpa
